name: smart_road_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_messaging: ^15.1.3
  firebase_storage: ^12.3.4
  firebase_database: ^11.1.2
  shared_preferences: ^2.3.3
  google_fonts: ^6.2.1
  geolocator: ^13.0.1
  geocoding: ^3.0.0
  http: ^1.2.2
  intl: ^0.20.2
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  qr_flutter: ^4.1.0
  flutter_local_notifications: ^18.0.1
  permission_handler: ^11.3.1
  open_filex: 4.7.0
  path_provider: ^2.1.4
  provider: ^6.1.5+1
  speech_to_text: ^7.3.0
  flutter_tts: ^3.6.0
  upi_pay: ^1.1.0
  google_sign_in: ^6.2.1
  printing: ^5.14.2
  sqflite: ^2.3.3+2
  avatar_glow: ^3.0.1
  sensors_plus: ^7.0.0
  camera: ^0.11.3
  confetti: ^0.8.0
  lottie: ^3.3.2

  path: any
  pdf: any
  flutter_dotenv: ^6.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true